// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DevBridge.Templates.WebProject.Web.Controllers {
    public partial class AgreementController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AgreementController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AgreementController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult List() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.List);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Create() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Create);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult WireJson() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.WireJson);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AgreementController Actions { get { return MVC.Agreement; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Agreement";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Agreement";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string List = "List";
            public readonly string Create = "Create";
            public readonly string WireJson = "WireJson";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string List = "List";
            public const string Create = "Create";
            public const string WireJson = "WireJson";
        }


        static readonly ActionParamsClass_List s_params_List = new ActionParamsClass_List();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_List ListParams { get { return s_params_List; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_List {
            public readonly string filter = "filter";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create {
            public readonly string createAgreement = "createAgreement";
        }
        static readonly ActionParamsClass_WireJson s_params_WireJson = new ActionParamsClass_WireJson();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WireJson WireJsonParams { get { return s_params_WireJson; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WireJson {
            public readonly string data = "data";
            public readonly string behavior = "behavior";
            public readonly string success = "success";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Create = "~/Views/Agreement/Create.cshtml";
            public readonly string List = "~/Views/Agreement/List.cshtml";
            static readonly _Partial s_Partial = new _Partial();
            public _Partial Partial { get { return s_Partial; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _Partial{
                public readonly string AgreementItem = "~/Views/Agreement/Partial/AgreementItem.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AgreementController: DevBridge.Templates.WebProject.Web.Controllers.AgreementController {
        public T4MVC_AgreementController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult List(DevBridge.Templates.WebProject.Web.Logic.Commands.Agreement.GetAgreements.GetAgreementsFilter filter) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.List);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filter", filter);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create(DevBridge.Templates.WebProject.Web.Logic.Models.Agreement.CreateAgreementViewModel createAgreement) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "createAgreement", createAgreement);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult WireJson(DevBridge.Templates.WebProject.Tools.Mvc.WireJson data, System.Web.Mvc.JsonRequestBehavior behavior) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.WireJson);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "behavior", behavior);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult WireJson(bool success, dynamic data, System.Web.Mvc.JsonRequestBehavior behavior) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.WireJson);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "success", success);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "behavior", behavior);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
